// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZO8HheKF4Rnot44Lh3QBWELgBq_hW3U',
    appId: '1:913827750855:web:3db9397a924ba3eff62fe2',
    messagingSenderId: '913827750855',
    projectId: 'tired-tire',
    authDomain: 'tired-tire.firebaseapp.com',
    storageBucket: 'tired-tire.firebasestorage.app',
    measurementId: 'G-4TJ1JG878F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Z0yHiMDbngT-kt9PgseHBYs3pHkrl0I',
    appId: '1:913827750855:android:02c0a4e5c1cd9fadf62fe2',
    messagingSenderId: '913827750855',
    projectId: 'tired-tire',
    storageBucket: 'tired-tire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqOuS458xNaV5nUGvw27Ifv5qwrWsjBuQ',
    appId: '1:913827750855:ios:545db0e038e2341af62fe2',
    messagingSenderId: '913827750855',
    projectId: 'tired-tire',
    storageBucket: 'tired-tire.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqOuS458xNaV5nUGvw27Ifv5qwrWsjBuQ',
    appId: '1:913827750855:ios:545db0e038e2341af62fe2',
    messagingSenderId: '913827750855',
    projectId: 'tired-tire',
    storageBucket: 'tired-tire.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZO8HheKF4Rnot44Lh3QBWELgBq_hW3U',
    appId: '1:913827750855:web:903223437ec4f295f62fe2',
    messagingSenderId: '913827750855',
    projectId: 'tired-tire',
    authDomain: 'tired-tire.firebaseapp.com',
    storageBucket: 'tired-tire.firebasestorage.app',
    measurementId: 'G-N79G369VKN',
  );
}
